version: '3.9'

services:
  # Base de données pour Airflow
  airflow-db:
    image: postgres:16
    environment:
      POSTGRES_USER: airflow
      POSTGRES_PASSWORD: airflow
      POSTGRES_DB: airflow
    volumes:
      - airflow_db_data:/var/lib/postgresql/data

  # Airflow (Webserver & Scheduler réunis )
  airflow:
    build: 
      context: .
      dockerfile: docker/Dockerfile.airflow
    depends_on:
      - airflow-db
    environment:
      - AIRFLOW__CORE__EXECUTOR:LocalExecutor
      - AIRFLOW__DATABASE__SQL_ALCHEMY_CONN=postgresql+psycopg2://airflow:airflow@airflow-db/airflow
      - AIRFLOW__CORE__LOAD_EXAMPLES=False
    ports:
      - "8080:8080"
    volumes:
      - ./airflow/dags:/opt/airflow/dags
      - ./airflow/scripts/entrypoint_init.sh:/init_airflow.sh
      - ./data:/opt/airflow/data
      - ./model:/opt/airflow/data/model
      # - shared_data:/app/data # volume partagé avec l'API
    command: bash -c "/init_airflow.sh && airflow standalone"

  # API de paiement
  api:
    build: 
      context: .
      dockerfile: docker/Dockerfile.api
    ports:
      - "8000:8000"
    volumes:
      - ./model:/app/data/model
      - ./data:/app/database
    depends_on:
      - airflow-db

  # MLflow
  mlflow:
      build:
          context: .
          dockerfile: docker/Dockerfile.mlflow
      ports:
          - "5000:5000"
      environment:
        - MLFLOW_HTTP_GATEWAY_ALLOWED_HEADERS=Host
        - MLFLOW_SERVER_GUNICORN_OPTS=--forwarded-allow-ips="*"
        - MLFLOW_HTTP_GATEWAY_ALLOWED_HOSTS=*
      volumes:
      - ./mlruns:/mlflow_data
      command: >
        mlflow server 
        --backend-store-uri file:///mlflow_data
        --default-artifact-root file:///mlflow_data
        --host 0.0.0.0 
        --port 5000


volumes:
  airflow_db_data:
  # shared_data: