FROM python:3.12-slim

ENV PYTHONDONTWRITEBYTECODE=1 \
    PYTHONUNBUFFERED=1

RUN apt-get update && apt-get install -y \
    build-essential \
    curl \
    git \
    && rm -rf /var/lib/apt/lists/* 

WORKDIR /app

COPY requirements/api.txt /tmp/api.txt
RUN pip install --upgrade pip \
    && pip install --no-cache-dir -r /tmp/api.txt

COPY ./api /app/api

EXPOSE 8000

CMD ["uvicorn", "api:app", "--host", "0.0.0.0", "--port", "8000"]
